const trains = [
  {
    id: 1,
    number: "IC 123",
    departureStation: "Leipzig",
    arrivalStation: "Berlin",
    departureTime: "08:30",
    price: 50,
  },
  {
    id: 2,
    number: "RE 456",
    departureStation: "Leipzig",
    arrivalStation: "Dresden",
    departureTime: "09:00",
    price: 30,
  },
  {
    id: 3,
    number: "ICE 789",
    departureStation: "Leipzig",
    arrivalStation: "Munich",
    departureTime: "09:30",
    price: 80,
  },
  {
    id: 4,
    number: "IC 234",
    departureStation: "Leipzig",
    arrivalStation: "Frankfurt",
    departureTime: "10:00",
    price: 60,
  },
  {
    id: 5,
    number: "RE 567",
    departureStation: "Leipzig",
    arrivalStation: "Halle",
    departureTime: "10:30",
    price: 20,
  },
  {
    id: 6,
    number: "ICE 890",
    departureStation: "Leipzig",
    arrivalStation: "Cologne",
    departureTime: "11:00",
    price: 90,
  },
  // Новые поезда
  {
    id: 7,
    number: "IC 345",
    departureStation: "Leipzig",
    arrivalStation: "Hamburg",
    departureTime: "11:30",
    price: 70,
  },
  {
    id: 8,
    number: "RE 678",
    departureStation: "Leipzig",
    arrivalStation: "Stuttgart",
    departureTime: "12:00",
    price: 40,
  },
  {
    id: 9,
    number: "ICE 901",
    departureStation: "Leipzig",
    arrivalStation: "Berlin",
    departureTime: "12:30",
    price: 55,
  },
  {
    id: 10,
    number: "IC 456",
    departureStation: "Leipzig",
    arrivalStation: "Munich",
    departureTime: "13:00",
    price: 85,
  },
  {
    id: 11,
    number: "RE 789",
    departureStation: "Leipzig",
    arrivalStation: "Frankfurt",
    departureTime: "13:30",
    price: 35,
  },
  {
    id: 12,
    number: "ICE 234",
    departureStation: "Leipzig",
    arrivalStation: "Cologne",
    departureTime: "14:00",
    price: 95,
  },
  {
    id: 13,
    number: "IC 567",
    departureStation: "Leipzig",
    arrivalStation: "Dresden",
    departureTime: "14:30",
    price: 45,
  },
  {
    id: 14,
    number: "RE 890",
    departureStation: "Leipzig",
    arrivalStation: "Hamburg",
    departureTime: "15:00",
    price: 60,
  },
  {
    id: 15,
    number: "ICE 345",
    departureStation: "Leipzig",
    arrivalStation: "Stuttgart",
    departureTime: "15:30",
    price: 75,
  },
  {
    id: 16,
    number: "IC 678",
    departureStation: "Leipzig",
    arrivalStation: "Berlin",
    departureTime: "16:00",
    price: 50,
  },
  {
    id: 17,
    number: "RE 901",
    departureStation: "Leipzig",
    arrivalStation: "Munich",
    departureTime: "16:30",
    price: 40,
  },
  {
    id: 18,
    number: "ICE 456",
    departureStation: "Leipzig",
    arrivalStation: "Frankfurt",
    departureTime: "17:00",
    price: 85,
  },
  {
    id: 19,
    number: "IC 789",
    departureStation: "Leipzig",
    arrivalStation: "Halle",
    departureTime: "17:30",
    price: 25,
  },
  {
    id: 20,
    number: "RE 234",
    departureStation: "Leipzig",
    arrivalStation: "Cologne",
    departureTime: "18:00",
    price: 55,
  },
  {
    id: 21,
    number: "ICE 678",
    departureStation: "Leipzig",
    arrivalStation: "Hamburg",
    departureTime: "18:30",
    price: 70,
  },
  {
    id: 22,
    number: "IC 901",
    departureStation: "Leipzig",
    arrivalStation: "Stuttgart",
    departureTime: "19:00",
    price: 80,
  },
  {
    id: 23,
    number: "RE 345",
    departureStation: "Leipzig",
    arrivalStation: "Berlin",
    departureTime: "19:30",
    price: 30,
  },
  {
    id: 24,
    number: "ICE 789",
    departureStation: "Leipzig",
    arrivalStation: "Munich",
    departureTime: "20:00",
    price: 90,
  },
  {
    id: 25,
    number: "IC 012",
    departureStation: "Leipzig",
    arrivalStation: "Frankfurt",
    departureTime: "20:30",
    price: 65,
  },
  {
    id: 26,
    number: "RE 456",
    departureStation: "Leipzig",
    arrivalStation: "Halle",
    departureTime: "21:00",
    price: 20,
  },
  {
    id: 27,
    number: "ICE 890",
    departureStation: "Leipzig",
    arrivalStation: "Cologne",
    departureTime: "21:30",
    price: 95,
  },
  {
    id: 28,
    number: "IC 123",
    departureStation: "Leipzig",
    arrivalStation: "Hamburg",
    departureTime: "22:00",
    price: 75,
  },
  {
    id: 29,
    number: "RE 678",
    departureStation: "Leipzig",
    arrivalStation: "Stuttgart",
    departureTime: "22:30",
    price: 45,
  },
  {
    id: 30,
    number: "ICE 012",
    departureStation: "Leipzig",
    arrivalStation: "Dresden",
    departureTime: "23:00",
    price: 60,
  },
];

export default trains;
